# Generated by Django 3.0.6 on 2020-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('ip', 'In Progress'), ('c', 'Completed')], default='In Progress', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
    ]
